controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api_login:
    path: /api/login   

api_restaurant_login: 
    path: /api/restaurant/login