version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "5173:80"

  backend:
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    volumes:
      - ./backend:/var/www/backend:rw
      - ./backend/var:/var/www/backend/var:rw
      - ./backend/public/uploads:/var/www/backend/public/uploads:rw

  mercure:
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_JWT_ALG: HS256
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous

  nginx:
    environment:
      - CERT_CN=${PUBLIC_IP:-localhost}
    volumes:
      - ./docker/nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:rw
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  database:
    volumes:
      - database_data_prod:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password --innodb-buffer-pool-size=256M

# phpMyAdmin excluded from production deployment

volumes:
  database_data_prod:
    driver: local 