api_platform:
    title: Hello API Platform
    version: 1.0.0
    # The paths where API Platform will look for resources.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
