mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: 'file://%env(resolve:JWT_SECRET_KEY)%'
                passphrase: '%env(JWT_PASSPHRASE)%'
                algorithm: 'rsa.sha256'
                publish: '*'
