# config/serialization/Article.yaml
App\Entity\Article:
    attributes:
        id:
            groups: ['article:read', 'article:read:collection']
        name:
            groups: ['article:read', 'article:read:collection']
        description:
            groups: ['article:read', 'article:read:collection'] 
        imageFilename:
            groups: ['article:read', 'article:read:collection']
        listed:
            groups: ['article:read', 'article:read:collection']
        price:
            groups: ['article:read', 'article:read:collection']
        allergies:
            groups: ['article:read', 'article:read:collection'] 
        available:
            groups: ['article:read', 'article:read:collection']
        restaurant:
            groups: ['article:read', 'restaurant:read:nested'] 
        restaurantId:
            groups: ['article:read:collection'] 