# config/serialization/Order.yaml
App\Entity\Order:
    attributes:
        id:
            groups: ['order:read', 'order:read:collection']
        created_at:
            groups: ['order:read', 'order:read:collection']
        status:
            groups: ['order:read', 'order:read:collection']
        total_price:
            groups: ['order:read', 'order:read:collection']
        items:
            groups: ['order:read'] # Only show full item details in single order view
        user:
            groups: ['order:read', 'order:read:collection'] # Use parent groups
        restaurant:
            groups: ['order:read', 'order:read:collection'] # Use parent groups
            # Use less detailed group, e.g., 'restaurant:read:nested' defined in Restaurant.yaml (id, name?) 